apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        backend:
          serviceName: firstapp
          servicePort: 80
      - path: /first(.*)
        backend:
          serviceName: firstapp
          servicePort: 80
      - path: /second(.*)
        backend:
          serviceName: secondapp
          servicePort: 80
