apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: *
    http:
      paths:
      - path: /first
        backend:
          serviceName: firstapp
          servicePort: 80
      - path: /second
        backend:
          serviceName: secondapp
          servicePort: 80
